system:
  config_path: "${PROJECT_ROOT}/configs/infer_cfg_combine.yml"
  device: gpu
  output_dir: '${PROJECT_ROOT}/storage/private/output'
  pushurl_prefix: rtsp://localhost:8554/paddle

detection:
  fight:
    config_path: "${PROJECT_ROOT}/configs/infer_cfg_pphuman.yml"
    snapshot:
      enabled: true
      output_dir: '${PROJECT_ROOT}/storage/private/snapshots/fight'
    mqtt:
      enabled: true
      event_topic_prefix: "fight_detection/events"
      command_topic_prefix: "fight_detection/cmd"
      state_topic_prefix: "fight_detection/state"

  vehicle_plate:
    config_path: "${PROJECT_ROOT}/configs/infer_cfg_ppvehicle.yml"
    snapshot:
      enabled: true
      output_dir: '${PROJECT_ROOT}/storage/private/snapshots/vehicle_plate'
    mqtt:
      enabled: true
      event_topic_prefix: "vehicle_plate_detection/events"
      command_topic_prefix: "vehicle_plate_detection/cmd"
      state_topic_prefix: "vehicle_plate_detection/state"
